// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvoqthpivljtvbitkujd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2b3F0aHBpdmxqdHZiaXRrdWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTU1MTQsImV4cCI6MjA2Mzc3MTUxNH0.e-NrI7dvd-_k8Jfu6Op2JgUzCWXeGQ8zqD5-97Ra9o0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);